version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
    environment:
      CC: clang
      CXX: clang++
  gcc:
    docker:
    - image: fost/circleci
    environment:
      CC: gcc-10
      CXX: g++-10

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: install
          command: apt-get install -y golang
      - run:
          name: cmake
          environment:
            CMAKE_BUILD_TYPE: << parameters.variant >>
          command: |
            mkdir build.tmp
            cd build.tmp
            cmake .. -G Ninja
      - run:
          name: ninja
          command: ninja -j1 -C build.tmp

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
